package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

// serviceCmd represents the service command
var serviceCmd = &cobra.Command{
	Use:   "service",
	Short: "Check for new PagerDuty event on all available services",
	Long:  "Check for new Pagerduty checker event generated by pd-checker-event",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("service called")
	},
}

func init() {
	rootCmd.AddCommand(serviceCmd)
	viper.AutomaticEnv()
	serviceCmd.PersistentFlags().String("pagerduty_auth_token", "", "Set your PagerDuty auth Token")
}
